version: "3.9"
services:
    boenergo-server:
      build: .
      command: python manage.py runserver 0.0.0.0:9000
      volumes:
        - .:/boenergo_project
      ports: 
        - 9000:9000
      environment:
        - SECRET_KEY=RAnDoM_SeCrET_KeY_313_323_463
        - DEBUG=False
        - ALLOWED_HOSTS=127.0.0.1,localhost
